databases:
  - name: flask-postgres
    databaseName: flask_db
    user: flask_user

services:
  - type: web
    name: flask-demo-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true